# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGNmNjk4ODQyNDVjYjVmNWE2YTc1ZGNiM2I5Y2RkNzI2NDFhNDUzZDFjMGMwZDBkOWNjYzEyYzkyN2VlZWJlZTAxYjEzYWI0MDYxNzI3NzhhYzIzNDBjMmRjMDU2ZTA2NzMzNGFiYjExODgwNWZiNzllODc4MmQ3YzMyMTJjYTY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
