#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to Consul running in Docker

jhipster:
  security:
    oauth2:
      audience: https://dev-06bzs1cu.us.auth0.com/api/v2/
spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-06bzs1cu.us.auth0.com/ # make sure to include the trailing slash!
        registration:
          oidc:
            client-id: QLPXGHrEUMgylcwYb4sejIR8DBcwstob
            client-secret: SoiCAMAZbJGIIdzIWTd1yUmsMn7Rm38fzW62PCuGZfoubwmWoUDTHbl1GEm7L8B6
